"""The football-data.co.uk downloader — football/downloader.py.

Two invariants carry the weight here. **A file is validated before it is
written**, so a format change is caught at download time rather than months
later inside an analysis; and **a response that is not a season file never
reaches disk under a .csv name** — an HTML error page served with a 200 is the
realistic failure, and pandas will happily parse one into a one-column frame.

The network is never touched: `fetch_csv` is replaced with a function serving
text generated by `football/sample_data.py`, which writes football-data's own
column shape.
"""

import os

import pandas as pd
import pytest

from football.downloader import (
    DownloadError,
    LEAGUES,
    download_extra,
    download_seasons,
    inspect,
    parse_leagues,
    parse_season,
    parse_seasons,
    read_season_csv,
    season_code,
    season_label,
    season_path,
    season_start_year,
    write_season,
)
from football.sample_data import generate_matches

CORE_CSV = ("Div,Date,HomeTeam,AwayTeam,FTHG,FTAG\n"
            "E0,09/08/2019,Arsenal,Burnley,2,1\n"
            "E0,10/08/2019,Chelsea,Fulham,1,1\n")


def season_csv(closing=True, n_teams=6):
    """One synthetic season in football-data's shape, as CSV text."""
    raw = generate_matches(n_teams=n_teams, seed=1, closing_odds=closing)
    return raw.drop(columns=["TrueH", "TrueD", "TrueA"]).to_csv(index=False)


# ------------------------------------------------------------------- seasons

def test_season_codes_round_trip():
    for year in (1993, 1999, 2000, 2019, 2024):
        assert season_start_year(season_code(year)) == year


def test_a_season_is_accepted_in_every_form_a_person_types():
    assert {parse_season(t) for t in ("2324", "2023/24", "2023-24", "2023")} == {"2324"}


def test_the_archive_start_is_a_stated_limit_not_a_silent_clamp():
    with pytest.raises(ValueError, match="predates"):
        season_code(1990)


def test_a_range_needs_dots_or_two_full_years():
    assert parse_seasons("2019/20..2021/22") == ["1920", "2021", "2122"]
    # Both sides of a `-` range are season *start* years, as with `..`.
    assert parse_seasons("2019-2022") == ["1920", "2021", "2122", "2223"]
    # The ambiguous case, resolved the way it reads: one season, not two.
    assert parse_seasons("2019-2020") == ["1920"]


def test_seasons_come_back_chronological_and_deduplicated():
    assert parse_seasons("2324,2023/24,2019/20") == ["1920", "2324"]


def test_a_backwards_range_is_refused():
    with pytest.raises(ValueError, match="ends before"):
        parse_seasons("2021/22..2019/20")


def test_season_labels_are_printable():
    assert season_label("2324") == "2023/24"
    assert season_label("9900") == "1999/00"


# ------------------------------------------------------------------- leagues

def test_league_codes_are_normalised_and_deduplicated():
    assert parse_leagues("e0, SP1 ,E0") == ["E0", "SP1"]


def test_the_extra_league_files_are_refused_by_name():
    # ARG.csv exists on the site but carries Home/Away/HG/AG, a different
    # contract that football/processor.py does not read.
    with pytest.raises(ValueError, match="different column set"):
        parse_leagues("ARG")


def test_every_known_league_has_a_name_for_the_error_message():
    assert all(LEAGUES.values())


def test_extra_code_rejected_without_the_flag():
    with pytest.raises(ValueError):
        parse_leagues("COL")  # extra flag not set


def test_extra_codes_parse_with_the_flag():
    assert parse_leagues("COL,ARG", extra=True) == ["COL", "ARG"]


# ------------------------------------------------------------------ the guard

def test_an_html_error_page_is_never_parsed_as_a_season():
    with pytest.raises(DownloadError, match="is HTML, not CSV"):
        read_season_csv("<!DOCTYPE html>\n<html><body>Not found</body></html>")


def test_a_header_only_file_is_refused():
    with pytest.raises(DownloadError, match="no rows"):
        read_season_csv("Div,Date,HomeTeam,AwayTeam,FTHG,FTAG\n")


def test_trailing_blank_rows_and_unnamed_columns_are_dropped():
    df = read_season_csv(CORE_CSV.replace("\n", ",\n", 1).replace(
        "Div,Date", "Div,Date").rstrip() + "\n,,,,,\n")
    assert len(df) == 2
    assert not [c for c in df.columns if str(c).startswith("Unnamed:")]


def test_garbage_that_is_not_csv_is_refused():
    with pytest.raises(DownloadError):
        read_season_csv('a,b\n"unterminated\n1,2,3,4\n')


# ---------------------------------------------------------------- validation

def test_a_file_is_routed_through_the_contract_at_download_time():
    report = inspect(read_season_csv(season_csv(closing=True)))
    assert report["odds_source"] == "market_closing_average"
    assert report["odds_are_closing"] is True
    assert report["odds_coverage"] == 1.0
    assert report["n_matches"] > 0


def test_a_file_missing_the_contract_fails_the_download_not_the_analysis():
    from football.processor import MatchFormatError
    with pytest.raises(MatchFormatError, match="Missing required columns"):
        inspect(pd.DataFrame({"Date": ["09/08/2019"], "HomeTeam": ["Arsenal"]}))


def test_an_opening_odds_file_is_reported_as_such_rather_than_rejected():
    report = inspect(read_season_csv(season_csv(closing=False)))
    assert report["odds_source"] == "market_opening_average"
    assert report["odds_are_closing"] is False


# -------------------------------------------------------------------- writing

def test_the_file_is_written_exactly_as_downloaded(tmp_path):
    # The processor owns the contract; a downloader that pruned columns would
    # become a second, weaker owner of it.
    text = season_csv()
    path = str(tmp_path / "E0_2324.csv")
    write_season(text, path)
    assert open(path, encoding="utf-8").read() == text


def test_a_longer_file_is_not_replaced_by_a_shorter_one(tmp_path):
    path = str(tmp_path / "E0_2324.csv")
    write_season(season_csv(n_teams=8), path)
    with pytest.raises(DownloadError, match="Refusing to overwrite"):
        write_season(season_csv(n_teams=4), path)


def test_force_allows_the_shrink_when_the_source_really_lost_rows(tmp_path):
    path = str(tmp_path / "E0_2324.csv")
    write_season(season_csv(n_teams=8), path)
    write_season(season_csv(n_teams=4), path, force=True)
    assert len(read_season_csv(open(path, encoding="utf-8").read())) < 60


def test_an_in_progress_season_may_grow(tmp_path):
    path = str(tmp_path / "E0_2324.csv")
    write_season(season_csv(n_teams=4), path)
    write_season(season_csv(n_teams=8), path)   # no force needed


def test_the_path_names_the_league_and_season():
    assert season_path("2324", "E0", "d") == os.path.join("d", "E0_2324.csv")


# --------------------------------------------------------------- the driver

def fake_fetch(available):
    """A stand-in for fetch_csv: a dict of (season, league) -> text, else None."""
    def fetch(season, league, session=None, **kwargs):
        return available.get((season, league))
    return fetch


def test_a_missing_league_season_is_skipped_not_fatal(tmp_path, monkeypatch):
    monkeypatch.setattr("football.downloader.fetch_csv",
                        fake_fetch({("2324", "E0"): season_csv()}))
    summary = download_seasons(["2223", "2324"], ["E0"], out_dir=str(tmp_path), delay=0)
    assert list(summary["season"]) == ["2023/24"]
    assert os.path.exists(str(tmp_path / "E0_2324.csv"))


def test_nothing_downloaded_at_all_raises(tmp_path, monkeypatch):
    monkeypatch.setattr("football.downloader.fetch_csv", fake_fetch({}))
    with pytest.raises(DownloadError, match="Nothing was obtained"):
        download_seasons(["2324"], ["E0"], out_dir=str(tmp_path), delay=0)


def test_dry_run_writes_nothing_but_still_validates(tmp_path, monkeypatch):
    monkeypatch.setattr("football.downloader.fetch_csv",
                        fake_fetch({("2324", "E0"): season_csv()}))
    summary = download_seasons(["2324"], ["E0"], out_dir=str(tmp_path), delay=0, dry_run=True)
    assert summary.loc[0, "n_matches"] > 0
    assert summary.loc[0, "path"] == ""
    assert not os.listdir(tmp_path)


def test_closing_odds_only_skips_the_soft_seasons(tmp_path, monkeypatch):
    monkeypatch.setattr("football.downloader.fetch_csv", fake_fetch({
        ("1819", "E0"): season_csv(closing=False),
        ("2324", "E0"): season_csv(closing=True),
    }))
    summary = download_seasons(["1819", "2324"], ["E0"], out_dir=str(tmp_path),
                               delay=0, closing_odds_only=True)
    assert list(summary["season"]) == ["2023/24"]
    assert os.listdir(tmp_path) == ["E0_2324.csv"]


# --------------------------------------------------------------- extra files

EXTRA_FIXTURE = os.path.join(os.path.dirname(__file__), "fixtures", "new_COL_sample.csv")


def test_download_extra_handles_a_real_multi_league_file(tmp_path, monkeypatch):
    # Every real extra file stacks several leagues (COL = Primera A + Primera B).
    # The download-time check must validate ONE league, not choke on the file it
    # exists to fetch. Regression: download_extra used to pass league=None.
    text = open(EXTRA_FIXTURE, encoding="utf-8").read()
    monkeypatch.setattr("football.downloader._fetch_text",
                        lambda url, session=None, **kw: text)
    # The soft-baseline warning fires because the file carries opening odds — pin it.
    with pytest.warns(UserWarning, match="opening"):
        summary = download_extra(["COL"], out_dir=str(tmp_path), dry_run=True)
    assert list(summary["code"]) == ["COL"]
    assert "Colombia Primera A" in summary.loc[0, "leagues"]
    assert "Colombia Primera B" in summary.loc[0, "leagues"]
    assert not bool(summary.loc[0, "odds_are_closing"])
    assert not os.listdir(tmp_path)  # dry-run writes nothing


def test_the_summary_records_the_odds_source_per_file(tmp_path, monkeypatch):
    # Two sources in one summary is the warning sign: load_seasons will refuse
    # to load these together, and seeing it now beats finding out mid-evaluation.
    monkeypatch.setattr("football.downloader.fetch_csv", fake_fetch({
        ("1819", "E0"): season_csv(closing=False),
        ("2324", "E0"): season_csv(closing=True),
    }))
    summary = download_seasons(["1819", "2324"], ["E0"], out_dir=str(tmp_path), delay=0)
    assert set(summary["odds_source"]) == {"market_opening_average", "market_closing_average"}
    assert list(summary["odds_are_closing"]) == [False, True]
